wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.10
    cli_version: 0.17.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1731100093
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 23
      4: 3.11.10
      5: 0.17.4
      8:
      - 5
      13: linux-x86_64
batch_size:
  desc: null
  value: 32
learning_rate:
  desc: null
  value: 0.0002628412949576
optimizer:
  desc: null
  value: SGD
momentum:
  desc: null
  value: 0.6755105738841647
weight_decay:
  desc: null
  value: 0.0056753916231329
num_epochs:
  desc: null
  value: 30
